# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.4.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/abbot/go-http-auth"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/foomo/htpasswd"

[[constraint]]
  branch = "default"
  name = "bitbucket.org/gohg/gohg"

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.0.0"
